/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ImageMagick.h
 #	source generated by 4D Plugin Wizard
 #	Project : ImageMagick
 #	author : miyako
 #	2020/06/15
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_IMAGEMAGICK_H
#define PLUGIN_IMAGEMAGICK_H

#include "4DPluginAPI.h"

#include "C_BLOB.h"
#include "C_TEXT.h"
#include "C_REAL.h"

#include "ARRAY_TEXT.h"

#include "C_LONGINT.h"

#pragma mark -

#include <mutex>

#include "IMImage2.h"

IMImage2 *_objectCreate(uint32_t *index);
IMImage2 *_objectGet(uint32_t i);
void _objectDelete(uint32_t i);

#pragma mark -

void IM_New_Object(PA_PluginParameters params);
void IM_Clear_Object(PA_PluginParameters params);
void IM_Copy(PA_PluginParameters params);
void IM_Create(PA_PluginParameters params);
void IM_Open_File(PA_PluginParameters params);
void IM_Save_File(PA_PluginParameters params);
void IM_Get_Image_Properties(PA_PluginParameters params);
void IM_Set_Image_Properties(PA_PluginParameters params);
void IM_Modify_Image(PA_PluginParameters params);
void IM_Open_Blob(PA_PluginParameters params);
void IM_Save_Blob(PA_PluginParameters params);
void IM_Draw(PA_PluginParameters params);
void IM_Get_Last_Error(PA_PluginParameters params);
void IM_Get_Format_List(PA_PluginParameters params);

#endif /* PLUGIN_IMAGEMAGICK_H */
